In [23]:
import numpy as np
from scipy.special import logsumexp as lse

In [18]:
a = np.random.normal(size=(3,3))
b = np.random.normal(size=(3,3))
c = 0.5,

In [19]:
a+b

array([[-0.38130083, -1.16099161,  0.87423292],
       [-1.17671597, -1.72319265, -1.82835382],
       [-1.32067404, -0.91261742, -1.24329171]])

In [21]:
a

array([[ 0.5306911 ,  0.78686625,  0.36759438],
       [-2.01449987, -2.24316882, -0.65706642],
       [-0.93178676,  0.70041552, -1.25489193]])

In [22]:
b

array([[-0.91199193, -1.94785786,  0.50663854],
       [ 0.8377839 ,  0.51997617, -1.1712874 ],
       [-0.38888727, -1.61303295,  0.01160022]])

In [27]:
for i in a:
    print(i)

[0.5306911  0.78686625 0.36759438]
[-2.01449987 -2.24316882 -0.65706642]
[-0.93178676  0.70041552 -1.25489193]
